application: yourgoogleappname
version: 10
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /app/.*
  script: home.app

- url: /(.*\.(gif|png|jpg|wav))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|wav))